vectra-ai-research/Halberd

.gitignore, Halberd.py, core/AttackPlaybookVisualizer.py, core/Automator.py, core/Local.py, pages/attack.py, pages/automator.py, pages/home.py, pages/schedules.py, requirements.txt
1. Feature to execute attack playbooks
2. Feature to create a new playbook from Halberd UI
3. Feature to import an existing playbook
4. Feature to export a playbook
5.  New "Automator" view to view and manage playbooks
6. Ability to add techniques to playbook directly from Attack view
7. Updated home page
8. Updated requirements
9. Updated readme
10. Updated initialization check
11. Updated ignore list
=> Attack Automation & Portability

Techniques/Azure/Dump_Automation_Account.py, Techniques/Azure/Dump_KeyVault.py, Techniques/Azure/Dump_StorageAccount.py, Techniques/Azure/Expose_Storage_Account.py, Techniques/Azure/Modify_Access_KeyVault.py, Techniques/Azure/Share_Storage_Account_Container.py, Techniques/Azure/Share_VM_Disk.py
- fixed api response parsing
- fixed incorrect quotes
- updated pretty response format
- added module description to all new techniques
=> Azure techniques updates

Halberd.py, attack_techniques/__init__.py, attack_techniques/azure/azure_abuse_azure_policy_to_disable_logging.py, attack_techniques/azure/azure_deploy_malicious_extension_on_vm.py, attack_techniques/azure/azure_enumerate_resource_groups.py, attack_techniques/azure/azure_enumerate_resources.py, attack_techniques/azure/azure_enumerate_vm_in_vmss.py, attack_techniques/azure/azure_enumerate_vmss.py, attack_techniques/azure/azure_execute_script_on_vm.py, attack_techniques/azure/azure_password_spray.py, attack_techniques/entra_id/entra_establish_access_as_user.py, attack_techniques/entra_id/entra_password_spray.py, core/azure/azure_access.py, core/entra/entra_token_manager.py, pages/access.py
6 new Azure techniques:
- Abuse Azure Policy - Disable Logging
- VM - Execute Scripts/Commands
-  VM - Deploy Malicious Extension
- Enumerate VM in VMSS
- Enumerate VMSS
- Enumerate Resource Groups 
4 techniques updated :
- Azure Password Spray
- Azure Enumerate Resources
- Entra Establish Access as User
- Entra Password Spray
Upgrades Access Manage
- Ability to delete access tokens and active sessions from within Halberd 
- - Delete Entra ID access token
- -  Delete AWS sessions
- - Logout Azure session
=> new techniques & access management updates

attack_techniques/__init__.py, attack_techniques/entra_id/entra_assign_app_permission.py, attack_techniques/entra_id/entra_enumerate_app_permissions.py, attack_techniques/m365/m365_send_outlook_email.py, core/entra/graph_request.py
- new entra id techniques
- updated GraphRequest class
- Updated technique description
=> New Entra ID techniques

attack_techniques/__init__.py, attack_techniques/azure/azure_assign_role.py, attack_techniques/azure/azure_remove_role_asignment.py
- updated technique - AzureAssignRole
- added new technique - AzureRemoveRoleAssignment
=> New techniques

Halberd.py, attack_techniques/azure/azure_enumerate_resources.py, attack_techniques/m365/m365_search_outlook_messages.py, core/Functions.py
Major change - 
Halberd technique execution output display - This update changes the display of outputs from simple text to a parsed card style output. All execution results are parsed and depending on the data format the information is displayed in individual cards inside the outputs div. 
Function changes - 
Function name changed from PlaybookVizGenerator to playbook_viz_generator
playbook_viz_generator function import updated in Halberd.py
Bug fixes - 
- Error handling for report generation from empty log file
- Handled playbook info display when no playbook is selected in automator 
- AzureEnumerateResources updated technique output
=> Output Display Change & Bug fixes

attack_techniques/entra_id/entra_assign_app_permission.py, attack_techniques/entra_id/entra_create_new_app.py
**2 techniques updated**
1. EntraCreateNewApp
- Added optional ability to create service principal for an app
- Module description updated 
2. EntraAssignAppPermission
- Added optional ability to perform consent grant on assigned permission
- Module description updated
=> Entra id techniques updated

attack_techniques/m365/m365_exfil_user_mailbox.py
Correct endpoint url creation based on the technique config inputs
=> fix(m365_technique): Handle search term keywords

Halberd.py, attack_techniques/azure/azure_enumerate_assigned_roles.py, attack_techniques/azure/azure_enumerate_vm.py, attack_techniques/azure/azure_execute_script_on_vm.py, pages/attack.py, pages/home.py
Updates technique description
Adds azure threat research matrix references
Adds optional filtering params to techniques
Minor updates to home page footer
Minor bug fix to access modal button
Minor update to analyze dashboard widget titles
=> Update Azure techniques & bug fixes

Halberd.py, core/Functions.py, core/playbook/playbook_step.py, pages/attack.py, pages/automator.py
A new automator page with enhanced capabilities and updated view
1. Updated automator layout
2. More dynamic UI to reflect realtime changes
3. New actions for playbook management
4. Updated playbook visualization
5. New callbacks added to support added Automator functionality
6. New function added
Additional changes - 
1. Minor change to Attack page layout
2. Redundant callbacks removed
3. Redundant core functions removed
=> Automator v2

Halberd.py, attack_techniques/m365/m365_deploy_mail_forwarding_rule.py, attack_techniques/m365/m365_search_teams_chat.py, core/Functions.py, pages/automator.py
Automator enhancements
- New feature to display realtime playbook execution progress on UI
- Adds new callbacks
- Adds new core functions
- Adds new elements to automator page 
Minor fixes
- M365DeployEmailFrwdRule : Technique input updated
- M365SearchTeamsChat: Technique input updated
=> Automator Enhancement: View playbook progress

attack_techniques/azure/azure_abuse_azure_policy_to_disable_logging.py
Add remediation task to the azure policy abuse technique
=> update abuse azure policy technique with remediation task

Halberd.py, assets/halberd.css, core/Constants.py, core/Functions.py, pages/attack.py, pages/attack_analyse.py, pages/attack_history.py, pages/automator.py, pages/dashboard/entity_map.py, pages/dashboard/recon_roles.py, pages/dashboard/recon_users.py, pages/home.py, pages/recon.py, pages/schedules.py, version.py
Implements a new enhanced UI. This implements new more intuitive screens, consistent text, consistent coloring and consistent elements across the Halberd application. The UI is also made more dynamic and responsive.  
- Implements a redesigned Attack view
- Implements a redesigned Automator view
- Adds CSS styling doc
- Adds a new dark theme across the app (its very cool)
- Fixes minor UI bugs in Automator
- Adds version file
=> Halberd 2.0.0 UI

attack_techniques/entra_id/entra_device_code_flow_auth.py, attack_techniques/entra_id/entra_establish_access_as_user.py, core/entra/entra_token_manager.py, core/entra/graph_request.py, requirements.txt
- Adds auto refresh of MS access token 
- Adds handling of rate limiting/throttling to Graph requests 
- Updates requirements
- Updates Entra ID initial access techniques to capture refresh tokens
=> MS Token Auto Refresh

assets/halberd.css, attack_techniques/azure/azure_enumerate_assigned_roles.py, attack_techniques/base_technique.py, attack_techniques/entra_id/entra_add_trusted_ip_config.py, attack_techniques/entra_id/entra_device_code_flow_auth.py, attack_techniques/entra_id/entra_establish_access_as_user.py, attack_techniques/m365/m365_deploy_mail_forwarding_rule.py, core/Functions.py
1. Adds support for new type of input field in technique configuration: Dropdown. 
2. Updates default value display in technique configuration
3. Handles missing token value in auth response
4. Updates description base class : TechniqueNote
5. Changes input field label for techniques: EntraAddTrustedIPConfig, M365DeployEmailFrwdRule
=> Multiple fixes

attack_techniques/__init__.py, attack_techniques/azure/azure_extract_cache_tokens.py, attack_techniques/entra_id/entra_abuse_family_refresh_token.py, attack_techniques/m365/m365_exfil_sharepoint_data.py
M365
- Exfiltrate Sharepoint Data : Allows exfiltration of data from all accessible or select Sharepoint sites
Azure
- Extract Tokens From Local Cache : Extracts access/refresh tokens from Azure cache on host
Entra ID
- Abuse Family Refresh Token : Abuses Microsoft family refresh token functionality to obtain access tokens for different Microsoft resources and client applications
=> 3 New Techniques

attack_techniques/__init__.py, attack_techniques/azure/azure_enumerate_storage_containers.py
Adds a new azure technique to the technique registry
Technique name: Enumerate Storage Account Containers
This technique enumerates all containers in a target storage account and analyzes their contents for additional information including access levels, size metrics, file types, and security configurations.
=> New Azure Technique: enumerate containers in a storage account

attack_techniques/__init__.py, attack_techniques/azure/azure_enumerate_key_vaults.py, attack_techniques/azure/azure_enumerate_logic_apps.py, attack_techniques/azure/azure_mass_resource_deletion.py, attack_techniques/azure/azure_modify_logic_app_trigger.py
**Adds 4 new Azure techniques**
1. AzureMassResourceDeletion
2. AzureModifyLogicAppTrigger
3. AzureEnumerateLogicApps
4. AzureEnumerateKeyVaults
=> Azure techniques

attack_techniques/__init__.py, attack_techniques/gcp/gcp_persistence_via_ssh_key_addition.py, requirements.txt
Adds one GCP attack technique
Changes:
- Add GCP persistence technique using SSH key addition
- Align code with PEP 8 style guidelines
=> feat(gcp): Add persistence via SSH key addition

agent/attack_agent.py, assets/halberd.css, attack_techniques/azure/azure_assign_role.py, core/bootstrap.py, pages/attack_agent.py, run.py, version.py
Adds several visual and functionality enhancements to the Halberd attack agent - 
- Adds capability to add file attachments to agent chat
- Adds functionality to start new chat
- Adds functionality to store current chat when new chat is started
- Adds visual enhancements to view/manage attachments
- Redesigned Agent view with cleaner and more modern UI
- Improves rate limit handling
Additional minor changes - 
1. Add technique note to Azure technique : AzureAssignRole
2. Updates app version to 3.0.0
3. Updated initialization view on application start
4. Updated Azure CLI missing warning with clearer instructions
=> Attack Agent File Attachment Support

attack_techniques/__init__.py, attack_techniques/azure/azure_establish_access_via_device_code.py
Adds new Azure technique: AzureEstablishAccessViaDeviceCode
Description: Technique to establish access to Azure using device code flow
=> feat: New Azure technique

.dockerignore, .github/workflows/docker.yml, Dockerfile, README.md, attack_techniques/gcp/gcp_persistence_via_ssh_key_addition.py, docker-compose.yml
This PR implements robust Docker deployment capabilities for Halberd. Every merge to main branch will trigger an auto deployment and publishes to Github Container Registry. Enables platform agnostic, one line launch for users: 
`docker run -d --name halberd -p 8050:8050 ghcr.io/vectra-ai-research/halberd:latest` 
- `.dockerignore` (new)
- `.github/workflows/docker.yml` (new)
- `Dockerfile` (new)
- `docker-compose.yml` (new)
- `README.md` (updated with Docker instructions)
- `Dockerfile` : adds a multi-stage build process, it is used by the `docker.yml` workflow to deploy to the registry 
- `docker-compose.yml` : adds a easy way to build docker image locally. features health checks, resource limits, volume mounts
- `.github/workflows/docker.yml` : builds and pushes to the registry, also …
=> Add docker support

agent/attack_agent.py, halberd.py, pages/attack_agent.py
- Adds a new "Settings" off canvas to app to configure app settings
- Adds ability to configure anthropic API keys directly from UI eliminating the need to manually set env variables
=> Adds Halberd app configuration to UI

.github/workflows/docker.yml, Dockerfile
This PR introduces build system improvements for Halberd, focusing on Docker containerization enhancements and github pipeline optimization. 
- Build time reduced from 26 minutes to 6 minutes (77% improvement)
- Multi-stage Docker build with wheel pre-compilation & native runners
- Advanced GitHub Actions caching strategy
- `docker buildx bake`
- Add SBOM generation to each attestation
- Conditional logic in workflow (eg: if PR only build one platform)
=> Github Workflow Optimizations

README.md
Update readme - 
- Add halberd 3.0 gif
- Updated halberd description
=> refactor(readme): Update readme

agent/attack_agent.py, agent/tools.py
1. Improves token tracking
2. Implements enhanced rate limiting
3. Minimizes response delays from the agent
4. Adds web search tool to the agent
=> Halberd Attack Agent Improvement
